### ISSUE TITLE
Crash when moving from Game Preview to Game

### ISSUE THREAD

**Issue by fdavison1** [Friday-Night-Lite/friday-night-lite#9]
Something in the closeMenu function appears to cause the crash when navigating away from the page - presumably because the Modal component no longer exists (is null).

![error](https://user-images.githubusercontent.com/55988413/71057244-53ad8080-2119-11ea-9b82-34233d24ceb2.jpg)

**Comment by Chazensign** [comment]
Changed document assignment for close with 'click'.
